/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{vue,js,ts,jsx,tsx}"],
  theme: {
    extend: {
      screens: {
        tablet: "750px",
        phone: "900px",
        laptop: "1100px",
        desktop: "1280px",
      },
      fontFamily: {
        libreFranklin: ["Libre Franklin", "sans-serif"],
        bebasNeue: ["Bebas Neue", "sans-serif"],
        roboto: ["Roboto", "sans-serif"],
        inter: ["Inter", "sans-serif"],
        arial: ["Arial", "sans-serif"],
        poppins: ["Poppins", "sans-serif"],
        dmSans: ["DM Sans", "sans-serif"],
        manrope: ["Manrope", "sans-serif"],
      },
      width: {
        1: "1px",
        46: "46%",
        365: "365px",
        400: "400px",
        436: "436px",
        480: "480px",
        537: "537px",
        600: "600px",
        648: "648px",
        700: "700px",
        1400: "1400px",
      },
      height: {
        1: "1px",
        288: "288px",
        300: "300px",
        374: "374px",
        406: "406px",
        418: "418px",
        465: "465px",
        612: "612px",
      },
      margin: {
        155: "155px",
      },
      fontSize: {
        22: "22px",
        40: "40px",
      },
      colors: {
        m_white: "#BAC7D8",
        m_blue: "#003DA6",
        m_blue_2: "#5FA3D3",
        m_blue_3: "#5990A5",
        m_blue_4: "#0126B2",
        m_blue_5: "#011D92",
        m_blue_6: "#043EA1",
        m_bg_blue: "#001363",
        m_bg_blue_2: "#0223AB",
        m_bg_blue_3: "#011E62",
        m_bg_blue_4: "#021B80",
        m_bg_blue_5: "#0126B3",
        m_black: "#0C1736",
        m_black_2: "#212529",
        m_black_3: "#262626",
        m_gray: "#5485AF",
        m_gray_2: "#A1AAC6",
        m_gray_3: "#919396",
        m_gray_4: "#787878",
        m_gray_5: "#AFAFAF",
        m_gray_6: "#C6C6C6",
        m_gray_7: "#BCBCBC",
        m_bg_gray: "#EDEDED",
        m_bg_gray_2: "#F1F1F1",
        m_bg_gray_3: "#FAFAFA",
        m_bg_gray_4: "#7C7C7C",
        m_bg_gray_5: "#F5F5F5",
        m_bg_gray_6: "#626262",
        m_bg_gray_7: "#26262699",
        m_bg_gray_8: "#EBEEF3",
        m_green: "#527F71",
        m_red: "#CD0303",
      },
      backgroundImage: {
        "custom-gradient-1":
          "linear-gradient(to right, #021E91 10%,  #001982 50%, #0223AB 100%)",
        image: "url('/img/bg-img2.png')",
      },
      animation: {
        "fade-in": "fadeIn 0.8s ease-out forwards",
        "slide-up": "slideUp 0.6s ease-out forwards",
        "scale-in": "scaleIn 0.5s ease-out forwards",
        'fade-right': 'fadeRight 0.5s ease-out forwards',
        'fade-left': 'fadeLeft 0.5s ease-out forwards',
        counter: "counter 2s ease-out forwards",
      },
      keyframes: {
        fadeIn: {
          "0%": { opacity: "0", transform: "translateY(20px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
        slideUp: {
          "0%": { opacity: "0", transform: "translateY(30px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
        scaleIn: {
          "0%": { opacity: "0", transform: "scale(0.9)" },
          "100%": { opacity: "1", transform: "scale(1)" },
        },
        counter: {
          "0%": { opacity: "0" },
          "100%": { opacity: "1" },
        },
        fadeRight: {
          '0%': { opacity: '0', transform: 'translateX(-20px)' },
          '100%': { opacity: '1', transform: 'translateX(0)' }
        },
        fadeLeft: {
          '0%': { opacity: '0', transform: 'translateX(20px)' },
          '100%': { opacity: '1', transform: 'translateX(0)' },
        }
      },
      container: {
        padding: "4rem",
        center: true,
        screens: {
          sm: "100%",
          md: "100%",
          lg: "100%",
          xl: "100%",
          "2xl": "1536px",
        },
      },
      borderWidth: {
        DEFAULT: "1px",
        0: "0",
        2: "2px",
        3: "3px",
        4: "4px",
        6: "6px",
        8: "8px",
      },
    },
    plugins: [],
  },
};
